# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 300))
        Form.setMaximumSize(QtCore.QSize(500, 300))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(480, 290))
        self.tabWidget.setMaximumSize(QtCore.QSize(480, 290))
        self.tabWidget.setObjectName("tabWidget")
        self.Quick_tab = QtWidgets.QWidget()
        self.Quick_tab.setEnabled(True)
        self.Quick_tab.setAutoFillBackground(False)
        self.Quick_tab.setObjectName("Quick_tab")
        self.widget_2 = QtWidgets.QWidget(self.Quick_tab)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 474, 260))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qrcode_view = QtWidgets.QGraphicsView(self.widget_2)
        self.qrcode_view.setMaximumSize(QtCore.QSize(128, 128))
        self.qrcode_view.setObjectName("qrcode_view")
        self.horizontalLayout_2.addWidget(self.qrcode_view)
        self.account_table = QtWidgets.QTableWidget(self.widget_2)
        self.account_table.setObjectName("account_table")
        self.account_table.setColumnCount(0)
        self.account_table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.account_table)
        self.tabWidget.addTab(self.Quick_tab, "")
        self.Username_tab = QtWidgets.QWidget()
        self.Username_tab.setEnabled(False)
        self.Username_tab.setObjectName("Username_tab")
        self.widget = QtWidgets.QWidget(self.Username_tab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 474, 265))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(50, 10, 50, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Username = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Username.sizePolicy().hasHeightForWidth())
        self.Username.setSizePolicy(sizePolicy)
        self.Username.setMinimumSize(QtCore.QSize(0, 40))
        self.Username.setObjectName("Username")
        self.verticalLayout_2.addWidget(self.Username)
        self.Password = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Password.sizePolicy().hasHeightForWidth())
        self.Password.setSizePolicy(sizePolicy)
        self.Password.setMinimumSize(QtCore.QSize(0, 40))
        self.Password.setObjectName("Password")
        self.verticalLayout_2.addWidget(self.Password)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.tabWidget.addTab(self.Username_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Quick_tab), _translate("Form", "快捷登录"))
        self.Username.setPlaceholderText(_translate("Form", "支持QQ号/邮箱/手机号登录"))
        self.Password.setPlaceholderText(_translate("Form", "密码"))
        self.pushButton.setText(_translate("Form", "登录（功能停用）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Username_tab), _translate("Form", "账号密码登录"))
